#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : gnome-terminal
Version  : 3.54.3
Release  : 58
URL      : https://download.gnome.org/sources/gnome-terminal/3.54/gnome-terminal-3.54.3.tar.xz
Source0  : https://download.gnome.org/sources/gnome-terminal/3.54/gnome-terminal-3.54.3.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-4.0 GFDL-1.3 GPL-3.0 LGPL-3.0 MIT
Requires: gnome-terminal-bin = %{version}-%{release}
Requires: gnome-terminal-data = %{version}-%{release}
Requires: gnome-terminal-libexec = %{version}-%{release}
Requires: gnome-terminal-license = %{version}-%{release}
Requires: gnome-terminal-locales = %{version}-%{release}
Requires: gnome-terminal-man = %{version}-%{release}
Requires: gnome-terminal-services = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : dconf-dev
BuildRequires : desktop-file-utils
BuildRequires : docbook-xml
BuildRequires : gnome-shell
BuildRequires : gnome-terminal-doc
BuildRequires : gsettings-desktop-schemas-dev
BuildRequires : itstool
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(gsettings-desktop-schemas)
BuildRequires : pkgconfig(libhandy-1)
BuildRequires : pkgconfig(uuid)
BuildRequires : vte-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
GNOME Terminal
==============
CI status
---------
[![pipeline status](https://gitlab.gnome.org/GNOME/gnome-terminal/badges/master/pipeline.svg)](https://gitlab.gnome.org/GNOME/gnome-terminal/-/commits/master)

%package bin
Summary: bin components for the gnome-terminal package.
Group: Binaries
Requires: gnome-terminal-data = %{version}-%{release}
Requires: gnome-terminal-libexec = %{version}-%{release}
Requires: gnome-terminal-license = %{version}-%{release}
Requires: gnome-terminal-services = %{version}-%{release}

%description bin
bin components for the gnome-terminal package.


%package data
Summary: data components for the gnome-terminal package.
Group: Data

%description data
data components for the gnome-terminal package.


%package doc
Summary: doc components for the gnome-terminal package.
Group: Documentation
Requires: gnome-terminal-man = %{version}-%{release}

%description doc
doc components for the gnome-terminal package.


%package libexec
Summary: libexec components for the gnome-terminal package.
Group: Default
Requires: gnome-terminal-license = %{version}-%{release}

%description libexec
libexec components for the gnome-terminal package.


%package license
Summary: license components for the gnome-terminal package.
Group: Default

%description license
license components for the gnome-terminal package.


%package locales
Summary: locales components for the gnome-terminal package.
Group: Default

%description locales
locales components for the gnome-terminal package.


%package man
Summary: man components for the gnome-terminal package.
Group: Default

%description man
man components for the gnome-terminal package.


%package services
Summary: services components for the gnome-terminal package.
Group: Systemd services
Requires: systemd

%description services
services components for the gnome-terminal package.


%prep
%setup -q -n gnome-terminal-3.54.3
cd %{_builddir}/gnome-terminal-3.54.3
pushd ..
cp -a gnome-terminal-3.54.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738006338
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dnautilus_extension=false  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dnautilus_extension=false  builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-terminal
cp %{_builddir}/gnome-terminal-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gnome-terminal/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/gnome-terminal-%{version}/COPYING.GFDL %{buildroot}/usr/share/package-licenses/gnome-terminal/715f995f11805ee85601834220c43b082f457ea3 || :
cp %{_builddir}/gnome-terminal-%{version}/subprojects/vte/COPYING.CC-BY-4-0 %{buildroot}/usr/share/package-licenses/gnome-terminal/c0e2f3021a02d71ef52b88aac2ed98c996d7517d || :
cp %{_builddir}/gnome-terminal-%{version}/subprojects/vte/COPYING.GPL3 %{buildroot}/usr/share/package-licenses/gnome-terminal/a742ddd48b78f2a7a13ac678ce5ecacf93c771ee || :
cp %{_builddir}/gnome-terminal-%{version}/subprojects/vte/COPYING.LGPL3 %{buildroot}/usr/share/package-licenses/gnome-terminal/e203d4ef09d404fa5c03cf6590e44231665be689 || :
cp %{_builddir}/gnome-terminal-%{version}/subprojects/vte/COPYING.XTERM %{buildroot}/usr/share/package-licenses/gnome-terminal/704ec162c7e726301bf2b873fa99052b40250a99 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-terminal
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/gnome-terminal/gschemas.compiled

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gnome-terminal
/usr/bin/gnome-terminal

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.Terminal.Preferences.desktop
/usr/share/applications/org.gnome.Terminal.desktop
/usr/share/dbus-1/services/org.gnome.Terminal.service
/usr/share/glib-2.0/schemas/org.gnome.Terminal.gschema.xml
/usr/share/gnome-shell/search-providers/gnome-terminal-search-provider.ini
/usr/share/icons/hicolor/scalable/apps/org.gnome.Terminal.Preferences.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Terminal.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Terminal-symbolic.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Terminal.Preferences-symbolic.svg
/usr/share/metainfo/org.gnome.Terminal.Nautilus.metainfo.xml
/usr/share/metainfo/org.gnome.Terminal.metainfo.xml
/usr/share/xdg-terminals/org.gnome.Terminal.desktop

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/C/gnome-terminal/app-colors.page
/usr/share/help/C/gnome-terminal/app-cursor.page
/usr/share/help/C/gnome-terminal/app-fonts.page
/usr/share/help/C/gnome-terminal/app-fullscreen.page
/usr/share/help/C/gnome-terminal/app-terminal-sizes.page
/usr/share/help/C/gnome-terminal/app-zoom.page
/usr/share/help/C/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/C/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/C/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/C/gnome-terminal/gs-execute-commands.page
/usr/share/help/C/gnome-terminal/gs-tabs.page
/usr/share/help/C/gnome-terminal/index.page
/usr/share/help/C/gnome-terminal/introduction.page
/usr/share/help/C/gnome-terminal/legal.xml
/usr/share/help/C/gnome-terminal/overview.page
/usr/share/help/C/gnome-terminal/pref-bell.page
/usr/share/help/C/gnome-terminal/pref-custom-command.page
/usr/share/help/C/gnome-terminal/pref-custom-exit.page
/usr/share/help/C/gnome-terminal/pref-keyboard-access.page
/usr/share/help/C/gnome-terminal/pref-login-shell.page
/usr/share/help/C/gnome-terminal/pref-menubar.page
/usr/share/help/C/gnome-terminal/pref-profile-char-width.page
/usr/share/help/C/gnome-terminal/pref-profile-encoding.page
/usr/share/help/C/gnome-terminal/pref-profiles.page
/usr/share/help/C/gnome-terminal/pref-scrolling.page
/usr/share/help/C/gnome-terminal/pref-tab-window.page
/usr/share/help/C/gnome-terminal/pref-user-input.page
/usr/share/help/C/gnome-terminal/pref.page
/usr/share/help/C/gnome-terminal/prob-reset.page
/usr/share/help/C/gnome-terminal/txt-copy-paste.page
/usr/share/help/C/gnome-terminal/txt-links.page
/usr/share/help/C/gnome-terminal/txt-search.page
/usr/share/help/C/gnome-terminal/txt-select-text.page
/usr/share/help/ca/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/ca/gnome-terminal/app-colors.page
/usr/share/help/ca/gnome-terminal/app-cursor.page
/usr/share/help/ca/gnome-terminal/app-fonts.page
/usr/share/help/ca/gnome-terminal/app-fullscreen.page
/usr/share/help/ca/gnome-terminal/app-terminal-sizes.page
/usr/share/help/ca/gnome-terminal/app-zoom.page
/usr/share/help/ca/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/ca/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/ca/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/ca/gnome-terminal/gs-execute-commands.page
/usr/share/help/ca/gnome-terminal/gs-tabs.page
/usr/share/help/ca/gnome-terminal/index.page
/usr/share/help/ca/gnome-terminal/introduction.page
/usr/share/help/ca/gnome-terminal/legal.xml
/usr/share/help/ca/gnome-terminal/overview.page
/usr/share/help/ca/gnome-terminal/pref-bell.page
/usr/share/help/ca/gnome-terminal/pref-custom-command.page
/usr/share/help/ca/gnome-terminal/pref-custom-exit.page
/usr/share/help/ca/gnome-terminal/pref-keyboard-access.page
/usr/share/help/ca/gnome-terminal/pref-login-shell.page
/usr/share/help/ca/gnome-terminal/pref-menubar.page
/usr/share/help/ca/gnome-terminal/pref-profile-char-width.page
/usr/share/help/ca/gnome-terminal/pref-profile-encoding.page
/usr/share/help/ca/gnome-terminal/pref-profiles.page
/usr/share/help/ca/gnome-terminal/pref-scrolling.page
/usr/share/help/ca/gnome-terminal/pref-tab-window.page
/usr/share/help/ca/gnome-terminal/pref-user-input.page
/usr/share/help/ca/gnome-terminal/pref.page
/usr/share/help/ca/gnome-terminal/prob-reset.page
/usr/share/help/ca/gnome-terminal/txt-copy-paste.page
/usr/share/help/ca/gnome-terminal/txt-links.page
/usr/share/help/ca/gnome-terminal/txt-search.page
/usr/share/help/ca/gnome-terminal/txt-select-text.page
/usr/share/help/cs/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/cs/gnome-terminal/app-colors.page
/usr/share/help/cs/gnome-terminal/app-cursor.page
/usr/share/help/cs/gnome-terminal/app-fonts.page
/usr/share/help/cs/gnome-terminal/app-fullscreen.page
/usr/share/help/cs/gnome-terminal/app-terminal-sizes.page
/usr/share/help/cs/gnome-terminal/app-zoom.page
/usr/share/help/cs/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/cs/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/cs/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/cs/gnome-terminal/gs-execute-commands.page
/usr/share/help/cs/gnome-terminal/gs-tabs.page
/usr/share/help/cs/gnome-terminal/index.page
/usr/share/help/cs/gnome-terminal/introduction.page
/usr/share/help/cs/gnome-terminal/legal.xml
/usr/share/help/cs/gnome-terminal/overview.page
/usr/share/help/cs/gnome-terminal/pref-bell.page
/usr/share/help/cs/gnome-terminal/pref-custom-command.page
/usr/share/help/cs/gnome-terminal/pref-custom-exit.page
/usr/share/help/cs/gnome-terminal/pref-keyboard-access.page
/usr/share/help/cs/gnome-terminal/pref-login-shell.page
/usr/share/help/cs/gnome-terminal/pref-menubar.page
/usr/share/help/cs/gnome-terminal/pref-profile-char-width.page
/usr/share/help/cs/gnome-terminal/pref-profile-encoding.page
/usr/share/help/cs/gnome-terminal/pref-profiles.page
/usr/share/help/cs/gnome-terminal/pref-scrolling.page
/usr/share/help/cs/gnome-terminal/pref-tab-window.page
/usr/share/help/cs/gnome-terminal/pref-user-input.page
/usr/share/help/cs/gnome-terminal/pref.page
/usr/share/help/cs/gnome-terminal/prob-reset.page
/usr/share/help/cs/gnome-terminal/txt-copy-paste.page
/usr/share/help/cs/gnome-terminal/txt-links.page
/usr/share/help/cs/gnome-terminal/txt-search.page
/usr/share/help/cs/gnome-terminal/txt-select-text.page
/usr/share/help/da/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/da/gnome-terminal/app-colors.page
/usr/share/help/da/gnome-terminal/app-cursor.page
/usr/share/help/da/gnome-terminal/app-fonts.page
/usr/share/help/da/gnome-terminal/app-fullscreen.page
/usr/share/help/da/gnome-terminal/app-terminal-sizes.page
/usr/share/help/da/gnome-terminal/app-zoom.page
/usr/share/help/da/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/da/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/da/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/da/gnome-terminal/gs-execute-commands.page
/usr/share/help/da/gnome-terminal/gs-tabs.page
/usr/share/help/da/gnome-terminal/index.page
/usr/share/help/da/gnome-terminal/introduction.page
/usr/share/help/da/gnome-terminal/legal.xml
/usr/share/help/da/gnome-terminal/overview.page
/usr/share/help/da/gnome-terminal/pref-bell.page
/usr/share/help/da/gnome-terminal/pref-custom-command.page
/usr/share/help/da/gnome-terminal/pref-custom-exit.page
/usr/share/help/da/gnome-terminal/pref-keyboard-access.page
/usr/share/help/da/gnome-terminal/pref-login-shell.page
/usr/share/help/da/gnome-terminal/pref-menubar.page
/usr/share/help/da/gnome-terminal/pref-profile-char-width.page
/usr/share/help/da/gnome-terminal/pref-profile-encoding.page
/usr/share/help/da/gnome-terminal/pref-profiles.page
/usr/share/help/da/gnome-terminal/pref-scrolling.page
/usr/share/help/da/gnome-terminal/pref-tab-window.page
/usr/share/help/da/gnome-terminal/pref-user-input.page
/usr/share/help/da/gnome-terminal/pref.page
/usr/share/help/da/gnome-terminal/prob-reset.page
/usr/share/help/da/gnome-terminal/txt-copy-paste.page
/usr/share/help/da/gnome-terminal/txt-links.page
/usr/share/help/da/gnome-terminal/txt-search.page
/usr/share/help/da/gnome-terminal/txt-select-text.page
/usr/share/help/de/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/de/gnome-terminal/app-colors.page
/usr/share/help/de/gnome-terminal/app-cursor.page
/usr/share/help/de/gnome-terminal/app-fonts.page
/usr/share/help/de/gnome-terminal/app-fullscreen.page
/usr/share/help/de/gnome-terminal/app-terminal-sizes.page
/usr/share/help/de/gnome-terminal/app-zoom.page
/usr/share/help/de/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/de/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/de/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/de/gnome-terminal/gs-execute-commands.page
/usr/share/help/de/gnome-terminal/gs-tabs.page
/usr/share/help/de/gnome-terminal/index.page
/usr/share/help/de/gnome-terminal/introduction.page
/usr/share/help/de/gnome-terminal/legal.xml
/usr/share/help/de/gnome-terminal/overview.page
/usr/share/help/de/gnome-terminal/pref-bell.page
/usr/share/help/de/gnome-terminal/pref-custom-command.page
/usr/share/help/de/gnome-terminal/pref-custom-exit.page
/usr/share/help/de/gnome-terminal/pref-keyboard-access.page
/usr/share/help/de/gnome-terminal/pref-login-shell.page
/usr/share/help/de/gnome-terminal/pref-menubar.page
/usr/share/help/de/gnome-terminal/pref-profile-char-width.page
/usr/share/help/de/gnome-terminal/pref-profile-encoding.page
/usr/share/help/de/gnome-terminal/pref-profiles.page
/usr/share/help/de/gnome-terminal/pref-scrolling.page
/usr/share/help/de/gnome-terminal/pref-tab-window.page
/usr/share/help/de/gnome-terminal/pref-user-input.page
/usr/share/help/de/gnome-terminal/pref.page
/usr/share/help/de/gnome-terminal/prob-reset.page
/usr/share/help/de/gnome-terminal/txt-copy-paste.page
/usr/share/help/de/gnome-terminal/txt-links.page
/usr/share/help/de/gnome-terminal/txt-search.page
/usr/share/help/de/gnome-terminal/txt-select-text.page
/usr/share/help/el/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/el/gnome-terminal/app-colors.page
/usr/share/help/el/gnome-terminal/app-cursor.page
/usr/share/help/el/gnome-terminal/app-fonts.page
/usr/share/help/el/gnome-terminal/app-fullscreen.page
/usr/share/help/el/gnome-terminal/app-terminal-sizes.page
/usr/share/help/el/gnome-terminal/app-zoom.page
/usr/share/help/el/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/el/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/el/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/el/gnome-terminal/gs-execute-commands.page
/usr/share/help/el/gnome-terminal/gs-tabs.page
/usr/share/help/el/gnome-terminal/index.page
/usr/share/help/el/gnome-terminal/introduction.page
/usr/share/help/el/gnome-terminal/legal.xml
/usr/share/help/el/gnome-terminal/overview.page
/usr/share/help/el/gnome-terminal/pref-bell.page
/usr/share/help/el/gnome-terminal/pref-custom-command.page
/usr/share/help/el/gnome-terminal/pref-custom-exit.page
/usr/share/help/el/gnome-terminal/pref-keyboard-access.page
/usr/share/help/el/gnome-terminal/pref-login-shell.page
/usr/share/help/el/gnome-terminal/pref-menubar.page
/usr/share/help/el/gnome-terminal/pref-profile-char-width.page
/usr/share/help/el/gnome-terminal/pref-profile-encoding.page
/usr/share/help/el/gnome-terminal/pref-profiles.page
/usr/share/help/el/gnome-terminal/pref-scrolling.page
/usr/share/help/el/gnome-terminal/pref-tab-window.page
/usr/share/help/el/gnome-terminal/pref-user-input.page
/usr/share/help/el/gnome-terminal/pref.page
/usr/share/help/el/gnome-terminal/prob-reset.page
/usr/share/help/el/gnome-terminal/txt-copy-paste.page
/usr/share/help/el/gnome-terminal/txt-links.page
/usr/share/help/el/gnome-terminal/txt-search.page
/usr/share/help/el/gnome-terminal/txt-select-text.page
/usr/share/help/es/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/es/gnome-terminal/app-colors.page
/usr/share/help/es/gnome-terminal/app-cursor.page
/usr/share/help/es/gnome-terminal/app-fonts.page
/usr/share/help/es/gnome-terminal/app-fullscreen.page
/usr/share/help/es/gnome-terminal/app-terminal-sizes.page
/usr/share/help/es/gnome-terminal/app-zoom.page
/usr/share/help/es/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/es/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/es/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/es/gnome-terminal/gs-execute-commands.page
/usr/share/help/es/gnome-terminal/gs-tabs.page
/usr/share/help/es/gnome-terminal/index.page
/usr/share/help/es/gnome-terminal/introduction.page
/usr/share/help/es/gnome-terminal/legal.xml
/usr/share/help/es/gnome-terminal/overview.page
/usr/share/help/es/gnome-terminal/pref-bell.page
/usr/share/help/es/gnome-terminal/pref-custom-command.page
/usr/share/help/es/gnome-terminal/pref-custom-exit.page
/usr/share/help/es/gnome-terminal/pref-keyboard-access.page
/usr/share/help/es/gnome-terminal/pref-login-shell.page
/usr/share/help/es/gnome-terminal/pref-menubar.page
/usr/share/help/es/gnome-terminal/pref-profile-char-width.page
/usr/share/help/es/gnome-terminal/pref-profile-encoding.page
/usr/share/help/es/gnome-terminal/pref-profiles.page
/usr/share/help/es/gnome-terminal/pref-scrolling.page
/usr/share/help/es/gnome-terminal/pref-tab-window.page
/usr/share/help/es/gnome-terminal/pref-user-input.page
/usr/share/help/es/gnome-terminal/pref.page
/usr/share/help/es/gnome-terminal/prob-reset.page
/usr/share/help/es/gnome-terminal/txt-copy-paste.page
/usr/share/help/es/gnome-terminal/txt-links.page
/usr/share/help/es/gnome-terminal/txt-search.page
/usr/share/help/es/gnome-terminal/txt-select-text.page
/usr/share/help/eu/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/eu/gnome-terminal/app-colors.page
/usr/share/help/eu/gnome-terminal/app-cursor.page
/usr/share/help/eu/gnome-terminal/app-fonts.page
/usr/share/help/eu/gnome-terminal/app-fullscreen.page
/usr/share/help/eu/gnome-terminal/app-terminal-sizes.page
/usr/share/help/eu/gnome-terminal/app-zoom.page
/usr/share/help/eu/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/eu/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/eu/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/eu/gnome-terminal/gs-execute-commands.page
/usr/share/help/eu/gnome-terminal/gs-tabs.page
/usr/share/help/eu/gnome-terminal/index.page
/usr/share/help/eu/gnome-terminal/introduction.page
/usr/share/help/eu/gnome-terminal/legal.xml
/usr/share/help/eu/gnome-terminal/overview.page
/usr/share/help/eu/gnome-terminal/pref-bell.page
/usr/share/help/eu/gnome-terminal/pref-custom-command.page
/usr/share/help/eu/gnome-terminal/pref-custom-exit.page
/usr/share/help/eu/gnome-terminal/pref-keyboard-access.page
/usr/share/help/eu/gnome-terminal/pref-login-shell.page
/usr/share/help/eu/gnome-terminal/pref-menubar.page
/usr/share/help/eu/gnome-terminal/pref-profile-char-width.page
/usr/share/help/eu/gnome-terminal/pref-profile-encoding.page
/usr/share/help/eu/gnome-terminal/pref-profiles.page
/usr/share/help/eu/gnome-terminal/pref-scrolling.page
/usr/share/help/eu/gnome-terminal/pref-tab-window.page
/usr/share/help/eu/gnome-terminal/pref-user-input.page
/usr/share/help/eu/gnome-terminal/pref.page
/usr/share/help/eu/gnome-terminal/prob-reset.page
/usr/share/help/eu/gnome-terminal/txt-copy-paste.page
/usr/share/help/eu/gnome-terminal/txt-links.page
/usr/share/help/eu/gnome-terminal/txt-search.page
/usr/share/help/eu/gnome-terminal/txt-select-text.page
/usr/share/help/fi/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/fi/gnome-terminal/app-colors.page
/usr/share/help/fi/gnome-terminal/app-cursor.page
/usr/share/help/fi/gnome-terminal/app-fonts.page
/usr/share/help/fi/gnome-terminal/app-fullscreen.page
/usr/share/help/fi/gnome-terminal/app-terminal-sizes.page
/usr/share/help/fi/gnome-terminal/app-zoom.page
/usr/share/help/fi/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/fi/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/fi/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/fi/gnome-terminal/gs-execute-commands.page
/usr/share/help/fi/gnome-terminal/gs-tabs.page
/usr/share/help/fi/gnome-terminal/index.page
/usr/share/help/fi/gnome-terminal/introduction.page
/usr/share/help/fi/gnome-terminal/legal.xml
/usr/share/help/fi/gnome-terminal/overview.page
/usr/share/help/fi/gnome-terminal/pref-bell.page
/usr/share/help/fi/gnome-terminal/pref-custom-command.page
/usr/share/help/fi/gnome-terminal/pref-custom-exit.page
/usr/share/help/fi/gnome-terminal/pref-keyboard-access.page
/usr/share/help/fi/gnome-terminal/pref-login-shell.page
/usr/share/help/fi/gnome-terminal/pref-menubar.page
/usr/share/help/fi/gnome-terminal/pref-profile-char-width.page
/usr/share/help/fi/gnome-terminal/pref-profile-encoding.page
/usr/share/help/fi/gnome-terminal/pref-profiles.page
/usr/share/help/fi/gnome-terminal/pref-scrolling.page
/usr/share/help/fi/gnome-terminal/pref-tab-window.page
/usr/share/help/fi/gnome-terminal/pref-user-input.page
/usr/share/help/fi/gnome-terminal/pref.page
/usr/share/help/fi/gnome-terminal/prob-reset.page
/usr/share/help/fi/gnome-terminal/txt-copy-paste.page
/usr/share/help/fi/gnome-terminal/txt-links.page
/usr/share/help/fi/gnome-terminal/txt-search.page
/usr/share/help/fi/gnome-terminal/txt-select-text.page
/usr/share/help/fr/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/fr/gnome-terminal/app-colors.page
/usr/share/help/fr/gnome-terminal/app-cursor.page
/usr/share/help/fr/gnome-terminal/app-fonts.page
/usr/share/help/fr/gnome-terminal/app-fullscreen.page
/usr/share/help/fr/gnome-terminal/app-terminal-sizes.page
/usr/share/help/fr/gnome-terminal/app-zoom.page
/usr/share/help/fr/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/fr/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/fr/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/fr/gnome-terminal/gs-execute-commands.page
/usr/share/help/fr/gnome-terminal/gs-tabs.page
/usr/share/help/fr/gnome-terminal/index.page
/usr/share/help/fr/gnome-terminal/introduction.page
/usr/share/help/fr/gnome-terminal/legal.xml
/usr/share/help/fr/gnome-terminal/overview.page
/usr/share/help/fr/gnome-terminal/pref-bell.page
/usr/share/help/fr/gnome-terminal/pref-custom-command.page
/usr/share/help/fr/gnome-terminal/pref-custom-exit.page
/usr/share/help/fr/gnome-terminal/pref-keyboard-access.page
/usr/share/help/fr/gnome-terminal/pref-login-shell.page
/usr/share/help/fr/gnome-terminal/pref-menubar.page
/usr/share/help/fr/gnome-terminal/pref-profile-char-width.page
/usr/share/help/fr/gnome-terminal/pref-profile-encoding.page
/usr/share/help/fr/gnome-terminal/pref-profiles.page
/usr/share/help/fr/gnome-terminal/pref-scrolling.page
/usr/share/help/fr/gnome-terminal/pref-tab-window.page
/usr/share/help/fr/gnome-terminal/pref-user-input.page
/usr/share/help/fr/gnome-terminal/pref.page
/usr/share/help/fr/gnome-terminal/prob-reset.page
/usr/share/help/fr/gnome-terminal/txt-copy-paste.page
/usr/share/help/fr/gnome-terminal/txt-links.page
/usr/share/help/fr/gnome-terminal/txt-search.page
/usr/share/help/fr/gnome-terminal/txt-select-text.page
/usr/share/help/gl/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/gl/gnome-terminal/app-colors.page
/usr/share/help/gl/gnome-terminal/app-cursor.page
/usr/share/help/gl/gnome-terminal/app-fonts.page
/usr/share/help/gl/gnome-terminal/app-fullscreen.page
/usr/share/help/gl/gnome-terminal/app-terminal-sizes.page
/usr/share/help/gl/gnome-terminal/app-zoom.page
/usr/share/help/gl/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/gl/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/gl/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/gl/gnome-terminal/gs-execute-commands.page
/usr/share/help/gl/gnome-terminal/gs-tabs.page
/usr/share/help/gl/gnome-terminal/index.page
/usr/share/help/gl/gnome-terminal/introduction.page
/usr/share/help/gl/gnome-terminal/legal.xml
/usr/share/help/gl/gnome-terminal/overview.page
/usr/share/help/gl/gnome-terminal/pref-bell.page
/usr/share/help/gl/gnome-terminal/pref-custom-command.page
/usr/share/help/gl/gnome-terminal/pref-custom-exit.page
/usr/share/help/gl/gnome-terminal/pref-keyboard-access.page
/usr/share/help/gl/gnome-terminal/pref-login-shell.page
/usr/share/help/gl/gnome-terminal/pref-menubar.page
/usr/share/help/gl/gnome-terminal/pref-profile-char-width.page
/usr/share/help/gl/gnome-terminal/pref-profile-encoding.page
/usr/share/help/gl/gnome-terminal/pref-profiles.page
/usr/share/help/gl/gnome-terminal/pref-scrolling.page
/usr/share/help/gl/gnome-terminal/pref-tab-window.page
/usr/share/help/gl/gnome-terminal/pref-user-input.page
/usr/share/help/gl/gnome-terminal/pref.page
/usr/share/help/gl/gnome-terminal/prob-reset.page
/usr/share/help/gl/gnome-terminal/txt-copy-paste.page
/usr/share/help/gl/gnome-terminal/txt-links.page
/usr/share/help/gl/gnome-terminal/txt-search.page
/usr/share/help/gl/gnome-terminal/txt-select-text.page
/usr/share/help/hu/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/hu/gnome-terminal/app-colors.page
/usr/share/help/hu/gnome-terminal/app-cursor.page
/usr/share/help/hu/gnome-terminal/app-fonts.page
/usr/share/help/hu/gnome-terminal/app-fullscreen.page
/usr/share/help/hu/gnome-terminal/app-terminal-sizes.page
/usr/share/help/hu/gnome-terminal/app-zoom.page
/usr/share/help/hu/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/hu/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/hu/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/hu/gnome-terminal/gs-execute-commands.page
/usr/share/help/hu/gnome-terminal/gs-tabs.page
/usr/share/help/hu/gnome-terminal/index.page
/usr/share/help/hu/gnome-terminal/introduction.page
/usr/share/help/hu/gnome-terminal/legal.xml
/usr/share/help/hu/gnome-terminal/overview.page
/usr/share/help/hu/gnome-terminal/pref-bell.page
/usr/share/help/hu/gnome-terminal/pref-custom-command.page
/usr/share/help/hu/gnome-terminal/pref-custom-exit.page
/usr/share/help/hu/gnome-terminal/pref-keyboard-access.page
/usr/share/help/hu/gnome-terminal/pref-login-shell.page
/usr/share/help/hu/gnome-terminal/pref-menubar.page
/usr/share/help/hu/gnome-terminal/pref-profile-char-width.page
/usr/share/help/hu/gnome-terminal/pref-profile-encoding.page
/usr/share/help/hu/gnome-terminal/pref-profiles.page
/usr/share/help/hu/gnome-terminal/pref-scrolling.page
/usr/share/help/hu/gnome-terminal/pref-tab-window.page
/usr/share/help/hu/gnome-terminal/pref-user-input.page
/usr/share/help/hu/gnome-terminal/pref.page
/usr/share/help/hu/gnome-terminal/prob-reset.page
/usr/share/help/hu/gnome-terminal/txt-copy-paste.page
/usr/share/help/hu/gnome-terminal/txt-links.page
/usr/share/help/hu/gnome-terminal/txt-search.page
/usr/share/help/hu/gnome-terminal/txt-select-text.page
/usr/share/help/id/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/id/gnome-terminal/app-colors.page
/usr/share/help/id/gnome-terminal/app-cursor.page
/usr/share/help/id/gnome-terminal/app-fonts.page
/usr/share/help/id/gnome-terminal/app-fullscreen.page
/usr/share/help/id/gnome-terminal/app-terminal-sizes.page
/usr/share/help/id/gnome-terminal/app-zoom.page
/usr/share/help/id/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/id/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/id/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/id/gnome-terminal/gs-execute-commands.page
/usr/share/help/id/gnome-terminal/gs-tabs.page
/usr/share/help/id/gnome-terminal/index.page
/usr/share/help/id/gnome-terminal/introduction.page
/usr/share/help/id/gnome-terminal/legal.xml
/usr/share/help/id/gnome-terminal/overview.page
/usr/share/help/id/gnome-terminal/pref-bell.page
/usr/share/help/id/gnome-terminal/pref-custom-command.page
/usr/share/help/id/gnome-terminal/pref-custom-exit.page
/usr/share/help/id/gnome-terminal/pref-keyboard-access.page
/usr/share/help/id/gnome-terminal/pref-login-shell.page
/usr/share/help/id/gnome-terminal/pref-menubar.page
/usr/share/help/id/gnome-terminal/pref-profile-char-width.page
/usr/share/help/id/gnome-terminal/pref-profile-encoding.page
/usr/share/help/id/gnome-terminal/pref-profiles.page
/usr/share/help/id/gnome-terminal/pref-scrolling.page
/usr/share/help/id/gnome-terminal/pref-tab-window.page
/usr/share/help/id/gnome-terminal/pref-user-input.page
/usr/share/help/id/gnome-terminal/pref.page
/usr/share/help/id/gnome-terminal/prob-reset.page
/usr/share/help/id/gnome-terminal/txt-copy-paste.page
/usr/share/help/id/gnome-terminal/txt-links.page
/usr/share/help/id/gnome-terminal/txt-search.page
/usr/share/help/id/gnome-terminal/txt-select-text.page
/usr/share/help/ka/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/ka/gnome-terminal/app-colors.page
/usr/share/help/ka/gnome-terminal/app-cursor.page
/usr/share/help/ka/gnome-terminal/app-fonts.page
/usr/share/help/ka/gnome-terminal/app-fullscreen.page
/usr/share/help/ka/gnome-terminal/app-terminal-sizes.page
/usr/share/help/ka/gnome-terminal/app-zoom.page
/usr/share/help/ka/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/ka/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/ka/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/ka/gnome-terminal/gs-execute-commands.page
/usr/share/help/ka/gnome-terminal/gs-tabs.page
/usr/share/help/ka/gnome-terminal/index.page
/usr/share/help/ka/gnome-terminal/introduction.page
/usr/share/help/ka/gnome-terminal/legal.xml
/usr/share/help/ka/gnome-terminal/overview.page
/usr/share/help/ka/gnome-terminal/pref-bell.page
/usr/share/help/ka/gnome-terminal/pref-custom-command.page
/usr/share/help/ka/gnome-terminal/pref-custom-exit.page
/usr/share/help/ka/gnome-terminal/pref-keyboard-access.page
/usr/share/help/ka/gnome-terminal/pref-login-shell.page
/usr/share/help/ka/gnome-terminal/pref-menubar.page
/usr/share/help/ka/gnome-terminal/pref-profile-char-width.page
/usr/share/help/ka/gnome-terminal/pref-profile-encoding.page
/usr/share/help/ka/gnome-terminal/pref-profiles.page
/usr/share/help/ka/gnome-terminal/pref-scrolling.page
/usr/share/help/ka/gnome-terminal/pref-tab-window.page
/usr/share/help/ka/gnome-terminal/pref-user-input.page
/usr/share/help/ka/gnome-terminal/pref.page
/usr/share/help/ka/gnome-terminal/prob-reset.page
/usr/share/help/ka/gnome-terminal/txt-copy-paste.page
/usr/share/help/ka/gnome-terminal/txt-links.page
/usr/share/help/ka/gnome-terminal/txt-search.page
/usr/share/help/ka/gnome-terminal/txt-select-text.page
/usr/share/help/ko/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/ko/gnome-terminal/app-colors.page
/usr/share/help/ko/gnome-terminal/app-cursor.page
/usr/share/help/ko/gnome-terminal/app-fonts.page
/usr/share/help/ko/gnome-terminal/app-fullscreen.page
/usr/share/help/ko/gnome-terminal/app-terminal-sizes.page
/usr/share/help/ko/gnome-terminal/app-zoom.page
/usr/share/help/ko/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/ko/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/ko/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/ko/gnome-terminal/gs-execute-commands.page
/usr/share/help/ko/gnome-terminal/gs-tabs.page
/usr/share/help/ko/gnome-terminal/index.page
/usr/share/help/ko/gnome-terminal/introduction.page
/usr/share/help/ko/gnome-terminal/legal.xml
/usr/share/help/ko/gnome-terminal/overview.page
/usr/share/help/ko/gnome-terminal/pref-bell.page
/usr/share/help/ko/gnome-terminal/pref-custom-command.page
/usr/share/help/ko/gnome-terminal/pref-custom-exit.page
/usr/share/help/ko/gnome-terminal/pref-keyboard-access.page
/usr/share/help/ko/gnome-terminal/pref-login-shell.page
/usr/share/help/ko/gnome-terminal/pref-menubar.page
/usr/share/help/ko/gnome-terminal/pref-profile-char-width.page
/usr/share/help/ko/gnome-terminal/pref-profile-encoding.page
/usr/share/help/ko/gnome-terminal/pref-profiles.page
/usr/share/help/ko/gnome-terminal/pref-scrolling.page
/usr/share/help/ko/gnome-terminal/pref-tab-window.page
/usr/share/help/ko/gnome-terminal/pref-user-input.page
/usr/share/help/ko/gnome-terminal/pref.page
/usr/share/help/ko/gnome-terminal/prob-reset.page
/usr/share/help/ko/gnome-terminal/txt-copy-paste.page
/usr/share/help/ko/gnome-terminal/txt-links.page
/usr/share/help/ko/gnome-terminal/txt-search.page
/usr/share/help/ko/gnome-terminal/txt-select-text.page
/usr/share/help/pl/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/pl/gnome-terminal/app-colors.page
/usr/share/help/pl/gnome-terminal/app-cursor.page
/usr/share/help/pl/gnome-terminal/app-fonts.page
/usr/share/help/pl/gnome-terminal/app-fullscreen.page
/usr/share/help/pl/gnome-terminal/app-terminal-sizes.page
/usr/share/help/pl/gnome-terminal/app-zoom.page
/usr/share/help/pl/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/pl/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/pl/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/pl/gnome-terminal/gs-execute-commands.page
/usr/share/help/pl/gnome-terminal/gs-tabs.page
/usr/share/help/pl/gnome-terminal/index.page
/usr/share/help/pl/gnome-terminal/introduction.page
/usr/share/help/pl/gnome-terminal/legal.xml
/usr/share/help/pl/gnome-terminal/overview.page
/usr/share/help/pl/gnome-terminal/pref-bell.page
/usr/share/help/pl/gnome-terminal/pref-custom-command.page
/usr/share/help/pl/gnome-terminal/pref-custom-exit.page
/usr/share/help/pl/gnome-terminal/pref-keyboard-access.page
/usr/share/help/pl/gnome-terminal/pref-login-shell.page
/usr/share/help/pl/gnome-terminal/pref-menubar.page
/usr/share/help/pl/gnome-terminal/pref-profile-char-width.page
/usr/share/help/pl/gnome-terminal/pref-profile-encoding.page
/usr/share/help/pl/gnome-terminal/pref-profiles.page
/usr/share/help/pl/gnome-terminal/pref-scrolling.page
/usr/share/help/pl/gnome-terminal/pref-tab-window.page
/usr/share/help/pl/gnome-terminal/pref-user-input.page
/usr/share/help/pl/gnome-terminal/pref.page
/usr/share/help/pl/gnome-terminal/prob-reset.page
/usr/share/help/pl/gnome-terminal/txt-copy-paste.page
/usr/share/help/pl/gnome-terminal/txt-links.page
/usr/share/help/pl/gnome-terminal/txt-search.page
/usr/share/help/pl/gnome-terminal/txt-select-text.page
/usr/share/help/pt_BR/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/pt_BR/gnome-terminal/app-colors.page
/usr/share/help/pt_BR/gnome-terminal/app-cursor.page
/usr/share/help/pt_BR/gnome-terminal/app-fonts.page
/usr/share/help/pt_BR/gnome-terminal/app-fullscreen.page
/usr/share/help/pt_BR/gnome-terminal/app-terminal-sizes.page
/usr/share/help/pt_BR/gnome-terminal/app-zoom.page
/usr/share/help/pt_BR/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/pt_BR/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/pt_BR/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/pt_BR/gnome-terminal/gs-execute-commands.page
/usr/share/help/pt_BR/gnome-terminal/gs-tabs.page
/usr/share/help/pt_BR/gnome-terminal/index.page
/usr/share/help/pt_BR/gnome-terminal/introduction.page
/usr/share/help/pt_BR/gnome-terminal/legal.xml
/usr/share/help/pt_BR/gnome-terminal/overview.page
/usr/share/help/pt_BR/gnome-terminal/pref-bell.page
/usr/share/help/pt_BR/gnome-terminal/pref-custom-command.page
/usr/share/help/pt_BR/gnome-terminal/pref-custom-exit.page
/usr/share/help/pt_BR/gnome-terminal/pref-keyboard-access.page
/usr/share/help/pt_BR/gnome-terminal/pref-login-shell.page
/usr/share/help/pt_BR/gnome-terminal/pref-menubar.page
/usr/share/help/pt_BR/gnome-terminal/pref-profile-char-width.page
/usr/share/help/pt_BR/gnome-terminal/pref-profile-encoding.page
/usr/share/help/pt_BR/gnome-terminal/pref-profiles.page
/usr/share/help/pt_BR/gnome-terminal/pref-scrolling.page
/usr/share/help/pt_BR/gnome-terminal/pref-tab-window.page
/usr/share/help/pt_BR/gnome-terminal/pref-user-input.page
/usr/share/help/pt_BR/gnome-terminal/pref.page
/usr/share/help/pt_BR/gnome-terminal/prob-reset.page
/usr/share/help/pt_BR/gnome-terminal/txt-copy-paste.page
/usr/share/help/pt_BR/gnome-terminal/txt-links.page
/usr/share/help/pt_BR/gnome-terminal/txt-search.page
/usr/share/help/pt_BR/gnome-terminal/txt-select-text.page
/usr/share/help/ro/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/ro/gnome-terminal/app-colors.page
/usr/share/help/ro/gnome-terminal/app-cursor.page
/usr/share/help/ro/gnome-terminal/app-fonts.page
/usr/share/help/ro/gnome-terminal/app-fullscreen.page
/usr/share/help/ro/gnome-terminal/app-terminal-sizes.page
/usr/share/help/ro/gnome-terminal/app-zoom.page
/usr/share/help/ro/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/ro/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/ro/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/ro/gnome-terminal/gs-execute-commands.page
/usr/share/help/ro/gnome-terminal/gs-tabs.page
/usr/share/help/ro/gnome-terminal/index.page
/usr/share/help/ro/gnome-terminal/introduction.page
/usr/share/help/ro/gnome-terminal/legal.xml
/usr/share/help/ro/gnome-terminal/overview.page
/usr/share/help/ro/gnome-terminal/pref-bell.page
/usr/share/help/ro/gnome-terminal/pref-custom-command.page
/usr/share/help/ro/gnome-terminal/pref-custom-exit.page
/usr/share/help/ro/gnome-terminal/pref-keyboard-access.page
/usr/share/help/ro/gnome-terminal/pref-login-shell.page
/usr/share/help/ro/gnome-terminal/pref-menubar.page
/usr/share/help/ro/gnome-terminal/pref-profile-char-width.page
/usr/share/help/ro/gnome-terminal/pref-profile-encoding.page
/usr/share/help/ro/gnome-terminal/pref-profiles.page
/usr/share/help/ro/gnome-terminal/pref-scrolling.page
/usr/share/help/ro/gnome-terminal/pref-tab-window.page
/usr/share/help/ro/gnome-terminal/pref-user-input.page
/usr/share/help/ro/gnome-terminal/pref.page
/usr/share/help/ro/gnome-terminal/prob-reset.page
/usr/share/help/ro/gnome-terminal/txt-copy-paste.page
/usr/share/help/ro/gnome-terminal/txt-links.page
/usr/share/help/ro/gnome-terminal/txt-search.page
/usr/share/help/ro/gnome-terminal/txt-select-text.page
/usr/share/help/ru/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/ru/gnome-terminal/app-colors.page
/usr/share/help/ru/gnome-terminal/app-cursor.page
/usr/share/help/ru/gnome-terminal/app-fonts.page
/usr/share/help/ru/gnome-terminal/app-fullscreen.page
/usr/share/help/ru/gnome-terminal/app-terminal-sizes.page
/usr/share/help/ru/gnome-terminal/app-zoom.page
/usr/share/help/ru/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/ru/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/ru/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/ru/gnome-terminal/gs-execute-commands.page
/usr/share/help/ru/gnome-terminal/gs-tabs.page
/usr/share/help/ru/gnome-terminal/index.page
/usr/share/help/ru/gnome-terminal/introduction.page
/usr/share/help/ru/gnome-terminal/legal.xml
/usr/share/help/ru/gnome-terminal/overview.page
/usr/share/help/ru/gnome-terminal/pref-bell.page
/usr/share/help/ru/gnome-terminal/pref-custom-command.page
/usr/share/help/ru/gnome-terminal/pref-custom-exit.page
/usr/share/help/ru/gnome-terminal/pref-keyboard-access.page
/usr/share/help/ru/gnome-terminal/pref-login-shell.page
/usr/share/help/ru/gnome-terminal/pref-menubar.page
/usr/share/help/ru/gnome-terminal/pref-profile-char-width.page
/usr/share/help/ru/gnome-terminal/pref-profile-encoding.page
/usr/share/help/ru/gnome-terminal/pref-profiles.page
/usr/share/help/ru/gnome-terminal/pref-scrolling.page
/usr/share/help/ru/gnome-terminal/pref-tab-window.page
/usr/share/help/ru/gnome-terminal/pref-user-input.page
/usr/share/help/ru/gnome-terminal/pref.page
/usr/share/help/ru/gnome-terminal/prob-reset.page
/usr/share/help/ru/gnome-terminal/txt-copy-paste.page
/usr/share/help/ru/gnome-terminal/txt-links.page
/usr/share/help/ru/gnome-terminal/txt-search.page
/usr/share/help/ru/gnome-terminal/txt-select-text.page
/usr/share/help/sv/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/sv/gnome-terminal/app-colors.page
/usr/share/help/sv/gnome-terminal/app-cursor.page
/usr/share/help/sv/gnome-terminal/app-fonts.page
/usr/share/help/sv/gnome-terminal/app-fullscreen.page
/usr/share/help/sv/gnome-terminal/app-terminal-sizes.page
/usr/share/help/sv/gnome-terminal/app-zoom.page
/usr/share/help/sv/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/sv/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/sv/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/sv/gnome-terminal/gs-execute-commands.page
/usr/share/help/sv/gnome-terminal/gs-tabs.page
/usr/share/help/sv/gnome-terminal/index.page
/usr/share/help/sv/gnome-terminal/introduction.page
/usr/share/help/sv/gnome-terminal/legal.xml
/usr/share/help/sv/gnome-terminal/overview.page
/usr/share/help/sv/gnome-terminal/pref-bell.page
/usr/share/help/sv/gnome-terminal/pref-custom-command.page
/usr/share/help/sv/gnome-terminal/pref-custom-exit.page
/usr/share/help/sv/gnome-terminal/pref-keyboard-access.page
/usr/share/help/sv/gnome-terminal/pref-login-shell.page
/usr/share/help/sv/gnome-terminal/pref-menubar.page
/usr/share/help/sv/gnome-terminal/pref-profile-char-width.page
/usr/share/help/sv/gnome-terminal/pref-profile-encoding.page
/usr/share/help/sv/gnome-terminal/pref-profiles.page
/usr/share/help/sv/gnome-terminal/pref-scrolling.page
/usr/share/help/sv/gnome-terminal/pref-tab-window.page
/usr/share/help/sv/gnome-terminal/pref-user-input.page
/usr/share/help/sv/gnome-terminal/pref.page
/usr/share/help/sv/gnome-terminal/prob-reset.page
/usr/share/help/sv/gnome-terminal/txt-copy-paste.page
/usr/share/help/sv/gnome-terminal/txt-links.page
/usr/share/help/sv/gnome-terminal/txt-search.page
/usr/share/help/sv/gnome-terminal/txt-select-text.page
/usr/share/help/tr/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/tr/gnome-terminal/app-colors.page
/usr/share/help/tr/gnome-terminal/app-cursor.page
/usr/share/help/tr/gnome-terminal/app-fonts.page
/usr/share/help/tr/gnome-terminal/app-fullscreen.page
/usr/share/help/tr/gnome-terminal/app-terminal-sizes.page
/usr/share/help/tr/gnome-terminal/app-zoom.page
/usr/share/help/tr/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/tr/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/tr/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/tr/gnome-terminal/gs-execute-commands.page
/usr/share/help/tr/gnome-terminal/gs-tabs.page
/usr/share/help/tr/gnome-terminal/index.page
/usr/share/help/tr/gnome-terminal/introduction.page
/usr/share/help/tr/gnome-terminal/legal.xml
/usr/share/help/tr/gnome-terminal/overview.page
/usr/share/help/tr/gnome-terminal/pref-bell.page
/usr/share/help/tr/gnome-terminal/pref-custom-command.page
/usr/share/help/tr/gnome-terminal/pref-custom-exit.page
/usr/share/help/tr/gnome-terminal/pref-keyboard-access.page
/usr/share/help/tr/gnome-terminal/pref-login-shell.page
/usr/share/help/tr/gnome-terminal/pref-menubar.page
/usr/share/help/tr/gnome-terminal/pref-profile-char-width.page
/usr/share/help/tr/gnome-terminal/pref-profile-encoding.page
/usr/share/help/tr/gnome-terminal/pref-profiles.page
/usr/share/help/tr/gnome-terminal/pref-scrolling.page
/usr/share/help/tr/gnome-terminal/pref-tab-window.page
/usr/share/help/tr/gnome-terminal/pref-user-input.page
/usr/share/help/tr/gnome-terminal/pref.page
/usr/share/help/tr/gnome-terminal/prob-reset.page
/usr/share/help/tr/gnome-terminal/txt-copy-paste.page
/usr/share/help/tr/gnome-terminal/txt-links.page
/usr/share/help/tr/gnome-terminal/txt-search.page
/usr/share/help/tr/gnome-terminal/txt-select-text.page
/usr/share/help/uk/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/uk/gnome-terminal/app-colors.page
/usr/share/help/uk/gnome-terminal/app-cursor.page
/usr/share/help/uk/gnome-terminal/app-fonts.page
/usr/share/help/uk/gnome-terminal/app-fullscreen.page
/usr/share/help/uk/gnome-terminal/app-terminal-sizes.page
/usr/share/help/uk/gnome-terminal/app-zoom.page
/usr/share/help/uk/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/uk/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/uk/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/uk/gnome-terminal/gs-execute-commands.page
/usr/share/help/uk/gnome-terminal/gs-tabs.page
/usr/share/help/uk/gnome-terminal/index.page
/usr/share/help/uk/gnome-terminal/introduction.page
/usr/share/help/uk/gnome-terminal/legal.xml
/usr/share/help/uk/gnome-terminal/overview.page
/usr/share/help/uk/gnome-terminal/pref-bell.page
/usr/share/help/uk/gnome-terminal/pref-custom-command.page
/usr/share/help/uk/gnome-terminal/pref-custom-exit.page
/usr/share/help/uk/gnome-terminal/pref-keyboard-access.page
/usr/share/help/uk/gnome-terminal/pref-login-shell.page
/usr/share/help/uk/gnome-terminal/pref-menubar.page
/usr/share/help/uk/gnome-terminal/pref-profile-char-width.page
/usr/share/help/uk/gnome-terminal/pref-profile-encoding.page
/usr/share/help/uk/gnome-terminal/pref-profiles.page
/usr/share/help/uk/gnome-terminal/pref-scrolling.page
/usr/share/help/uk/gnome-terminal/pref-tab-window.page
/usr/share/help/uk/gnome-terminal/pref-user-input.page
/usr/share/help/uk/gnome-terminal/pref.page
/usr/share/help/uk/gnome-terminal/prob-reset.page
/usr/share/help/uk/gnome-terminal/txt-copy-paste.page
/usr/share/help/uk/gnome-terminal/txt-links.page
/usr/share/help/uk/gnome-terminal/txt-search.page
/usr/share/help/uk/gnome-terminal/txt-select-text.page
/usr/share/help/zh_CN/gnome-terminal/adv-keyboard-shortcuts.page
/usr/share/help/zh_CN/gnome-terminal/app-colors.page
/usr/share/help/zh_CN/gnome-terminal/app-cursor.page
/usr/share/help/zh_CN/gnome-terminal/app-fonts.page
/usr/share/help/zh_CN/gnome-terminal/app-fullscreen.page
/usr/share/help/zh_CN/gnome-terminal/app-terminal-sizes.page
/usr/share/help/zh_CN/gnome-terminal/app-zoom.page
/usr/share/help/zh_CN/gnome-terminal/figures/gnome-terminal.png
/usr/share/help/zh_CN/gnome-terminal/figures/keyboard-key-search.svg
/usr/share/help/zh_CN/gnome-terminal/figures/org.gnome.Terminal.svg
/usr/share/help/zh_CN/gnome-terminal/gs-execute-commands.page
/usr/share/help/zh_CN/gnome-terminal/gs-tabs.page
/usr/share/help/zh_CN/gnome-terminal/index.page
/usr/share/help/zh_CN/gnome-terminal/introduction.page
/usr/share/help/zh_CN/gnome-terminal/legal.xml
/usr/share/help/zh_CN/gnome-terminal/overview.page
/usr/share/help/zh_CN/gnome-terminal/pref-bell.page
/usr/share/help/zh_CN/gnome-terminal/pref-custom-command.page
/usr/share/help/zh_CN/gnome-terminal/pref-custom-exit.page
/usr/share/help/zh_CN/gnome-terminal/pref-keyboard-access.page
/usr/share/help/zh_CN/gnome-terminal/pref-login-shell.page
/usr/share/help/zh_CN/gnome-terminal/pref-menubar.page
/usr/share/help/zh_CN/gnome-terminal/pref-profile-char-width.page
/usr/share/help/zh_CN/gnome-terminal/pref-profile-encoding.page
/usr/share/help/zh_CN/gnome-terminal/pref-profiles.page
/usr/share/help/zh_CN/gnome-terminal/pref-scrolling.page
/usr/share/help/zh_CN/gnome-terminal/pref-tab-window.page
/usr/share/help/zh_CN/gnome-terminal/pref-user-input.page
/usr/share/help/zh_CN/gnome-terminal/pref.page
/usr/share/help/zh_CN/gnome-terminal/prob-reset.page
/usr/share/help/zh_CN/gnome-terminal/txt-copy-paste.page
/usr/share/help/zh_CN/gnome-terminal/txt-links.page
/usr/share/help/zh_CN/gnome-terminal/txt-search.page
/usr/share/help/zh_CN/gnome-terminal/txt-select-text.page

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/gnome-terminal-preferences
/V3/usr/libexec/gnome-terminal-server
/usr/libexec/gnome-terminal-preferences
/usr/libexec/gnome-terminal-server

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-terminal/704ec162c7e726301bf2b873fa99052b40250a99
/usr/share/package-licenses/gnome-terminal/715f995f11805ee85601834220c43b082f457ea3
/usr/share/package-licenses/gnome-terminal/842745cb706f8f2126506f544492f7a80dbe29b3
/usr/share/package-licenses/gnome-terminal/a742ddd48b78f2a7a13ac678ce5ecacf93c771ee
/usr/share/package-licenses/gnome-terminal/c0e2f3021a02d71ef52b88aac2ed98c996d7517d
/usr/share/package-licenses/gnome-terminal/e203d4ef09d404fa5c03cf6590e44231665be689

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gnome-terminal.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/gnome-terminal-server.service

%files locales -f gnome-terminal.lang
%defattr(-,root,root,-)

